package myclient;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://service/")
public class Exception_Exception extends java.lang.Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private myclient.Exception faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public Exception_Exception(String message, myclient.Exception faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public Exception_Exception(String message, myclient.Exception faultInfo,
			Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: myclient.Exception
	 */
	public myclient.Exception getFaultInfo() {
		return faultInfo;
	}

}
