package myclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "getresultbyidDelegate", targetNamespace = "http://service/")
public interface GetresultbyidDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Integer
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getResult", targetNamespace = "http://service/", className = "myclient.GetResult")
	@ResponseWrapper(localName = "getResultResponse", targetNamespace = "http://service/", className = "myclient.GetResultResponse")
	public Integer getResult(
			@WebParam(name = "arg0", targetNamespace = "") int arg0)
			throws Exception_Exception;

}
